# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instruction_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstructionWindow(object):
    def setupUi(self, InstructionWindow):
        InstructionWindow.setObjectName("InstructionWindow")
        InstructionWindow.resize(686, 600)
        self.centralwidget = QtWidgets.QWidget(InstructionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 651, 541))
        self.textEdit.setObjectName("textEdit")
        InstructionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InstructionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        InstructionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InstructionWindow)
        self.statusbar.setObjectName("statusbar")
        InstructionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InstructionWindow)
        QtCore.QMetaObject.connectSlotsByName(InstructionWindow)

    def retranslateUi(self, InstructionWindow):
        _translate = QtCore.QCoreApplication.translate
        InstructionWindow.setWindowTitle(_translate("InstructionWindow", "MainWindow"))
